<a href="https://colab.research.google.com/github/John-Fernand/TesteGit/blob/main/ProjetoIndividualPythonAn%C3%A1lisedeDados_ProjetoWeaponPicker.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Introdução:
Utilizarei a tabela spreadsheet abaixo. Os dados são fornecidos os dados de todas as armas do jogo.
A ideia do projeto foi utilizar POO e pandas para desenvolver um programa que filtrará as armas pelo status do jogo.

In [2]:
#Célula para importar as bibliotecas utilizadas e configurar o pandas.
import pandas as pd
import numpy as np #Importei o numpy pois achei que seria útil, acabei por não utilizar.

pd.set_option('display.max_columns', None) #Configuração  utilizada para mostrar o maior número de colunas possíveis.
pd.set_option('display.max_rows', None) #Configuração utilizada para mostrar o maior número de linhas possíveis.

In [ ]:
#Célula para importar os dados necessários, transformar em csv e ler o arquivo para o dataframe.
url = "https://docs.google.com/spreadsheets/d/1-sm_mSATMS0XFBG-dH3HhQcfM3dxh6hbLNR8Qe_1vaI/edit?gid=0#gid=0" #Link da tabela que foi utilizada.

planilha_id = "1-sm_mSATMS0XFBG-dH3HhQcfM3dxh6hbLNR8Qe_1vaI"

url_csv = (
    f"https://docs.google.com/spreadsheets/d/"
    f"{planilha_id}/export?format=csv&gid=0"
)

df = pd.read_csv(url_csv)

In [ ]:
'''Por conta da conversão da tabela, algumas colunas ficaram sem nomes, portanto, para organizar os dados, renomeei
as colunas para uma melhor compreensão.'''

#Status mínimos para utilizar a arma sem penalidades pesadas.
df = df.rename(columns={'Unnamed: 0': 'Weapon'}) #Nome da arma
df = df.rename(columns={'Requirements': 'Requirements STR'})#Requerimento de força.
df = df.rename(columns={'Unnamed: 2': 'Requirements DEX'})#Requerimento de destreza.
df = df.rename(columns={'Unnamed: 3': 'Requirements INT'})#Requerimento de inteligência.
df = df.rename(columns={'Unnamed: 4': 'Requirements FTH'})#Requerimento de fé.


df = df.rename(columns={'Unnamed: 5': 'Requirements Weight'})#Peso do item.
df = df.rename(columns={'Unnamed: 6': 'Crit dmg bonus'})#Multiplicador de dano extra em ataques críticos.

#Dano de tipos.
#físico, mágico, fogo, luz, e trevas.
df = df.rename(columns={'Normal +10/+5': 'Normal DMG +10/+5 Phy '}) #Armas podem ser melhoradas até o +10 ou +5 dependendo do tipo. Dano físico.
df = df.rename(columns={'Unnamed: 8': 'Normal DMG +10/+5 Magic'})#Dano mágico.
df = df.rename(columns={'Unnamed: 9': 'Normal DMG +10/+5 Fire'})#Dano de fogo.
df = df.rename(columns={'Unnamed: 10': 'Normal DMG +10/+5 Light'})#Dano de luz.
df = df.rename(columns={'Unnamed: 11': 'Normal DMG +10/+5 Dark'})#Dano de trevas.

#Dano de status negativos.
#Sangramento, veneno, e gelo.
df = df.rename(columns={'Auxiliary Damage': 'Auxiliary Damage Bleed'})#Dano de sangramento.
df = df.rename(columns={'Unnamed: 13': 'Auxiliary Damage Poison'})#Dano de veneno.
df = df.rename(columns={'Unnamed: 14': 'Auxiliary Damage Frost'})#Dano de gelo.

#Colunas renomeadas que tratam de Scaling.
#Quanto maior a classificação de do scaling de um status, mais aquele status irá influenciar no dano.
#Exemplo:
#em um personagem com 50 no status de força(STR ou Strength), uma arma com o scaling S
#terá um bonus pelo status muito maior do que uma arma com o scaling B.
df = df.rename(columns={'Scaling (+10/+5)': 'Scaling (+10/+5) STR'})
df = df.rename(columns={'Unnamed: 16': 'Scaling (+10/+5) DEX'})
df = df.rename(columns={'Unnamed: 17': 'Scaling (+10/+5) INT'})
df = df.rename(columns={'Unnamed: 18': 'Scaling (+10/+5) FTH'})

#Tipos de armas e dano.
df = df.rename(columns={'Unnamed: 19': 'Weapon Type'})
df = df.rename(columns={'Unnamed: 20': 'Damage Type'})

#
df = df.rename(columns={'Unnamed: 21': 'Skill'}) #Habilidade da arma.
df = df.rename(columns={'Unnamed: 22': 'Spell Buff'}) #Possível ou não amplificar a arma com magias.
df = df.rename(columns={'Unnamed: 23': 'Buffable' }) #Possível ou não infundir a arma.
df = df.rename(columns={'Unnamed: 24': 'Upgrade Material'}) #Material utilizado para melhorar a arma.
df = df.rename(columns={'Unnamed: 25': 'AR'})#Dano da arma.
df = df.rename(columns={'Unnamed: 26': 'Notes'})#Notas extras, algumas armas possuem efeitos especiais descritos nas notas.

In [ ]:
#Demonstração dos 5 primeiros itens dos dados.
df.head(5)

,Unnamed: 0,Requirements,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Normal +10/+5,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Auxiliary Damage,Unnamed: 13,Unnamed: 14,Scaling (+10/+5),Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26
0,Weapon,STR,DEX,INT,FTH,Units,Crit,Phy,Magic,Fire,Light,Dark,Bleed,Poison,Frost,S,Dx,I,F,Weapon Type,Damage Type,Skill,Spell Buff,Buffable,Upgrade Material,AR,Notes
1,Battle Axe,12,8,NaN,NaN,4,100,250,NaN,NaN,NaN,NaN,NaN,NaN,NaN,C,D,NaN,NaN,Axe,Standard,Warcry,NaN,Y,Titanite,433,NaN
2,Man Serpent Hatchet,16,13,NaN,NaN,4,100,250,NaN,NaN,NaN,NaN,NaN,NaN,NaN,C,D,NaN,NaN,Axe,Standard,Warcry,NaN,Y,Titanite,433,NaN
3,Brigand Axe,14,8,NaN,NaN,3,100,248,NaN,NaN,NaN,NaN,NaN,NaN,NaN,C,D,NaN,NaN,Axe,Standard,Warcry,NaN,Y,Titanite,432,NaN
4,Winged Knight Twinaxes,20,12,NaN,NaN,8.5,100,244,NaN,NaN,NaN,NaN,NaN,NaN,NaN,C,D,NaN,NaN,Axe,Standard,Chain Spin,NaN,Y,Titanite,423,NaN

In [ ]:
df.head(5) #Ver primeiras linhas.
df.tail(5) #Ver últimas linhas.
df.iloc[:,2] #Ver colunas especificas.

0      DEX
1        8
2       13
3        8
4       12
5        8
6        8
7      NaN
8        8
9       14
10      15
11      12
12      18
13      14
14      12
15      16
16      18
17      14
18       8
19       8
20      16
21      14
22       8
23       8
24      25
25      16
26      18
27      22
28      18
29      13
30      18
31      19
32      20
33      14
34      13
35      16
36      13
37      18
38      19
39      16
40      20
41      16
42      14
43      12
44      12
45       9
46       8
47       7
48       8
49      18
50      10
51      14
52       8
53       8
54     NaN
55     NaN
56     NaN
57     NaN
58     NaN
59     NaN
60     NaN
61     NaN
62      13
63     NaN
64       9
65     NaN
66     NaN
67      18
68      10
69       8
70     NaN
71      12
72     NaN
73      20
74      24
75      18
76      13
77      10
78      18
79      13
80      18
81       0
82      14
83      13
84      14
85      10
86      15
87      16
88      11
89      18
90      15
91      14
92      16
93      12
94      13
95      11
96      12
97      18
98       7
99      10
100      9
101    NaN
102     16
103    NaN
104     13
105     10
106     20
107     18
108     14
109     25
110     16
111     28
112     24
113     16
114     12
115     20
116     12
117     18
118     18
119     19
120     14
121    NaN
122    NaN
123    NaN
124    NaN
125    NaN
126    NaN
127     16
128     22
129     20
130     12
131     19
132     20
133     15
134     11
135     14
136     12
137     10
138     20
139     15
140     14
141     18
142     12
143     10
144     12
145    NaN
146    NaN
147    NaN
148    NaN
149    NaN
150    NaN
151    NaN
152    NaN
153    NaN
154    NaN
155     12
156     15
157     10
158     10
159     18
160     11
161     17
162     14
163     10
164     10
165     18
166     18
167     10
168      8
169     12
170    NaN
171    NaN
172    NaN
173    NaN
174    NaN
175    NaN
176     18
177     10
178     10
179     10
180     11
181     10
182     18
183     10
184     20
185     16
186     20
187     14
188     19
189     17
Name: Requirements DEX, dtype: object

In [ ]:
#Número de linhas
númerodeitens = (df.shape[0])
print(f"O número total de linhas, ou seja, de armas, é {númerodeitens - 1}.")
#Número de colunas
númerodecolunas = (df.shape[1])
print(f"O número total de colunas é de {númerodecolunas - 1}")
#Não estou contando os índices, portanto, fiz - 1.
#Obs: A quantidade de linhas verdadeiras seria -2, pois há uma linha que explica os status.

O número total de linhas, ou seja, de armas, é 189.
O número total de colunas é de 26

In [ ]:
#Utilizei POO
class Weaponpicker:

  def escolhertipoarma(self, df, listatiposarmas):#Método para definir o tipo de arma escolhido.
  #Utilizei o while e o try para executar até um valor válido ser inserido.
    continuar = True
    while continuar == True:
      try:
        print("Selecione o tipo de arma desejado.")
        y = 0
        for i in (listatiposarmas):
          print(f"{y} para escolher {i}.")
          y += 1
        tipodesejado = int(input("Qual dessas tipos gostaria de escolher?\nSó serão aceitos valores inteiros. "))
        if not 0 <= tipodesejado <= 23:
          raise ValueError
        continuar = False
        return tipodesejado
      except ValueError:
        print("Valor inválido, tente novamente.")

  def requerimentostatus(self, df, statusds):#Método para definir o status necessário para empunhar a arma, ambos qual o status necessário e qual o valor desse status.
    continuar = True
    continuar2 = True
    while continuar == True:
      try:
        print("Selecione o tipo de status que queira ver o requerimento minimo.")
        y = 0
        for i in (statusds):
          print(f"{y} para escolher {i}.")
          y += 1
        requerimentodesejado = int(input("Qual desses tipos gostaria de escolher?\nSó serão aceitos valores inteiros."))
        if not 0 <= requerimentodesejado <= 3:
          raise ValueError
        continuar2 = True
        while continuar2 == True:
          try:
            print("Selecione o valor do status. ")
            valorstatus = int(input("Há de ser de 1 a 99"))
            if not 1 <= valorstatus <= 99:
              raise ValueError
            continuar2 = False
            continuar = False #Só para ter certeza que vá funcionar
          except ValueError:
            print("Valor inválido, tente novamente.")
        continuar = False
        return requerimentodesejado, valorstatus
      except ValueError:
        print("Valor inválido, tente novamente.")

  def scalingdesejado(self, df, valorscaling, scalingtipo):#O valor de quanto o atributo escolhido afetará o dano e qual atributo será escolhido.
    continuar = True
    continuar2 = True
    while continuar == True:
        try:
          print("Selecione o tipo do scaling.")
          y = 0
          for i in (scalingtipo):
                print(f"{y} para escolher {i}.")
                y += 1
          scalingtipodesejado = int(input("Qual você deseja?"))
          if not 0 <= scalingtipodesejado < 5):
              raise ValueError
          while continuar2 == True:
            try:
              print("Selecione o valor do scaling.")
              y = 0
              for i in (valorscaling):
                print(f"{y} para escolher {i}.")
                y += 1
              scalingdesejado = int(input("Qual você deseja?"))
              if not 0 <= scalingdesejado <= 5:
                return ValueError
              continuar2 = False
              continuar = False
              return scalingdesejado, scalingtipodesejado2
            except ValueError:
              print("Valor inválido, tente novamente.")
        except ValueError:
              print("Valor inválido, tente novamente.")

  def filtragem(self, df, escolhertipoarma2, requerimentodesejado2, valorstatus2, scalingdesejado2, scalingtipodesejado2): #O filtro que será feito dos dados.
    df_filtro = df[
        (df["Weapon Type"] == listatiposarmas[escolhertipoarma2]) &
         (df[requerimentodesejado2] >= valorstatus2) &
          (df[scalingtipodesejado2] == scalingtipo[scalingdesejado2])]
    print(df_filtro)

  def menu(self):#Print das opções disponíveis.
    print("Qual operação deseja realizar?")
    print("(É necessário realizar todas pelo menos uma vez antes de executar a filtragem.)")
    print("1. Escolher o tipo de arma.")
    print("2. Escolher o requerimento de status.")
    print("3. Escolher o scaling desejado.")
    print("4. Executar a filtragem.")
    print("5. Encerrar o processo.")

  def executar(self, df):#Execução do código
    continuar = True
    escolhertipoarma2 = None
    requerimentodesejado2 = None
    valorstatus2 = None
    scalingdesejado2 = None
    scalingtipodesejado2 = None
    scalingtipo = ("Scaling (+10/+5) STR", "Scaling (+10/+5) DEX", "Scaling (+10/+5) INT", "Scaling (+10/+5) FTH")#Lista dos scalings. Por conta dos indices começarem no 0, as opções começam no 0.
    statusds = ("Requirements STR", "Requirements DEX", "Requirements INT", "Requirements FTH")#Lista de atributos de requerimento.
    valorscaling = ("E", "D", "C", "B", "A", "S")#Lista de valor de scaling.
    listatiposarmas = ("Axe", "Bow", "Claw", "Crossbow", "Curved Greatsword", "Curved Sword", "Dagger", "Fist", "Great Hammer", "Greataxe", "Greatbow", "Greatsword", "Halberd", "Hammer", "Katana", "Piercing Sword", "Reaper", "Sacred Chime", "Spear", "Staff", "Straigh Sword", "Talisman", "Ultra Greatsword", "Whip"  )#Lista tipo de armas.


    while continuar == True: #Loop while para execução.
      self.menu()
      escolha = input("Digite a opção desejada.")
      match escolha:
        case "1":
          escolhertipoarma2 = self.escolhertipoarma(df, listatiposarmas)
        case "2":
          requerimentodesejado2, valorstatus2 = self.requerimentostatus(df, statusds)
        case "3":
          scalingdesejado2, scalingtipodesejado2 = self.scalingdesejado(df, valorscaling, scalingtipo)
        case "4":
          if (escolhertipoarma2 is not None and requerimentodesejado2 is not None and scalingdesejado2 is not None):
            resultado = self.filtragem(df, listatiposarmas, escolhertipoarma2, statusds, requerimentodesejado2, valorstatus2, valorscaling, scalingtipo, scalingdesejado2, scalingtipodesejado2)
          else:
            print("Execute as opções 1, 2 e 3 antes de filtrar.")
        case "5":
          continuar = False
          print("Processo encerrado.")
        case _:
          print("Opção inválida.\nTente novamente.")

SyntaxError: unmatched ')' (1905085715.py, line 60)

Código anterior a essa célula de texto são o que eu escrevi manualmente a não ser que seja especificado.
Código de células posteriores são a versão corrigida funcional com chatgpt.
Por problemas com o filtro, o código anterior pode até rodar, porém o filtro não funciona.

In [3]:
#Código corrigido com chatgpt por leves problemas com filtro.
import pandas as pd
import numpy as np

planilha_id = "1-sm_mSATMS0XFBG-dH3HhQcfM3dxh6hbLNR8Qe_1vaI"
url_csv = f"https://docs.google.com/spreadsheets/d/{planilha_id}/export?format=csv&gid=0"

df = pd.read_csv(url_csv)

df = df.rename(columns={
    'Unnamed: 0': 'Weapon',
    'Requirements': 'Requirements STR',
    'Unnamed: 2': 'Requirements DEX',
    'Unnamed: 3': 'Requirements INT',
    'Unnamed: 4': 'Requirements FTH',
    'Unnamed: 5': 'Requirements Weight',
    'Unnamed: 6': 'Crit dmg bonus',
    'Normal +10/+5': 'Normal DMG +10/+5 Phy',
    'Unnamed: 8': 'Normal DMG +10/+5 Magic',
    'Unnamed: 9': 'Normal DMG +10/+5 Fire',
    'Unnamed: 10': 'Normal DMG +10/+5 Light',
    'Unnamed: 11': 'Normal DMG +10/+5 Dark',
    'Auxiliary Damage': 'Auxiliary Damage Bleed',
    'Unnamed: 13': 'Auxiliary Damage Poison',
    'Unnamed: 14': 'Auxiliary Damage Frost',
    'Scaling (+10/+5)': 'Scaling (+10/+5) STR',
    'Unnamed: 16': 'Scaling (+10/+5) DEX',
    'Unnamed: 17': 'Scaling (+10/+5) INT',
    'Unnamed: 18': 'Scaling (+10/+5) FTH',
    'Unnamed: 19': 'Weapon Type',
    'Unnamed: 20': 'Damage Type',
    'Unnamed: 21': 'Skill',
    'Unnamed: 22': 'Spell Buff',
    'Unnamed: 23': 'Buffable',
    'Unnamed: 24': 'Upgrade Material',
    'Unnamed: 25': 'AR',
    'Unnamed: 26': 'Notes'
})

print("Dados carregados:", len(df), "armas/linhas")
print("\nColunas disponíveis:")
print(df.columns.tolist())

print("\nTipos de arma encontrados:")
print(df["Weapon Type"].dropna().astype(str).str.strip().unique())

print("\nValores de scaling DEX:")
print(df["Scaling (+10/+5) DEX"].dropna().astype(str).str.strip().unique())

print("\nValores de scaling INT:")
print(df["Scaling (+10/+5) INT"].dropna().astype(str).str.strip().unique())

Dados carregados: 190 armas/linhas

Colunas disponíveis:
['Weapon', 'Requirements STR', 'Requirements DEX', 'Requirements INT', 'Requirements FTH', 'Requirements Weight', 'Crit dmg bonus', 'Normal DMG +10/+5 Phy', 'Normal DMG +10/+5 Magic', 'Normal DMG +10/+5 Fire', 'Normal DMG +10/+5 Light', 'Normal DMG +10/+5 Dark', 'Auxiliary Damage Bleed', 'Auxiliary Damage Poison', 'Auxiliary Damage Frost', 'Scaling (+10/+5) STR', 'Scaling (+10/+5) DEX', 'Scaling (+10/+5) INT', 'Scaling (+10/+5) FTH', 'Weapon Type', 'Damage Type', 'Skill', 'Spell Buff', 'Buffable', 'Upgrade Material', 'AR', 'Notes']

Tipos de arma encontrados:
['Weapon Type' 'Axe' 'Bow' 'Claw' 'Crossbow' 'Curved Greatsword'
 'Curved Sword' 'Dagger' 'Fist' 'Great Hammer' 'Greataxe' 'Greatbow'
 'Greatsword' 'Halberd' 'Hammer' 'Katana' 'Piercing Sword' 'Reaper'
 'Sacred Chime' 'Spear' 'Staff' 'Straight Sword' 'Talisman'
 'Ultra Greatsword' 'Whip']

Valores de scaling DEX:
['Dx' 'D' 'C' 'B' 'E' 'A' 'S']

Valores de scaling INT:
['I' 'B' 'D' 'E' 'C' 'A' 'S']

In [4]:
#Código corrigido com chatgpt por leves problemas com filtro.
class Weaponpicker:

  def escolhertipoarma(self, df, listatiposarmas):
    while True:
      try:
        print("\nSelecione o tipo de arma desejado.")

        for i, tipo in enumerate(listatiposarmas):
          print(f"{i} para escolher {tipo}.")

        tipodesejado = int(input("Digite o número do tipo de arma: "))

        if not 0 <= tipodesejado < len(listatiposarmas):
          raise ValueError

        return tipodesejado

      except ValueError:
        print("Valor inválido, tente novamente.")

  def requerimentostatus(self, df, statusds):
    while True:
      try:
        print("\nSelecione o atributo que deseja verificar.")

        for i, status in enumerate(statusds):
          print(f"{i} para escolher {status}.")

        requerimentodesejado = int(input("Digite o número do atributo: "))

        if not 0 <= requerimentodesejado < len(statusds):
          raise ValueError

        valorstatus = int(input("Digite o valor do seu status (1 a 99): "))

        if not 1 <= valorstatus <= 99:
          raise ValueError

        return requerimentodesejado, valorstatus

      except ValueError:
        print("Valor inválido. Tente novamente.")

  def scalingdesejado(self, df, valorscaling, scalingtipo):
    while True:
      try:
        print("\nSelecione o atributo do scaling.")

        for i, atributo in enumerate(scalingtipo):
          print(f"{i} para escolher {atributo}.")

        scalingtipodesejado = int(input("Digite o número do atributo: "))

        if not 0 <= scalingtipodesejado < len(scalingtipo):
          raise ValueError

        print("\nSelecione a letra de scaling desejada.")

        for i, letra in enumerate(valorscaling):
          print(f"{i} para escolher {letra}.")

        scalingdesejado = int(input("Digite o número da letra: "))

        if not 0 <= scalingdesejado < len(valorscaling):
          raise ValueError

        return scalingdesejado, scalingtipodesejado

      except ValueError:
        print("Valor inválido. Tente novamente.")

  def filtragem(
      self, df, listatiposarmas, escolhertipoarma2,
      statusds, requerimentodesejado2, valorstatus2,
      valorscaling, scalingtipo, scalingdesejado2,
      scalingtipodesejado2
  ):
    tipoarma = listatiposarmas[escolhertipoarma2]
    statusdesejado = statusds[requerimentodesejado2]
    coluna_scaling = scalingtipo[scalingtipodesejado2]
    valor_scaling = valorscaling[scalingdesejado2]

    # Normalizar texto para evitar diferenças de espaços e maiúsculas.
    tipos = df["Weapon Type"].astype("string").str.strip()
    escalas = (
        df[coluna_scaling]
        .astype("string")
        .str.strip()
        .str.upper()
    )

    # Converter os requisitos para números.
    requisitos = pd.to_numeric(df[statusdesejado], errors="coerce")

    # Criar cada filtro separadamente.
    filtro_tipo = tipos.str.casefold() == tipoarma.casefold()
    filtro_status = requisitos <= valorstatus2
    filtro_scaling = escalas == valor_scaling

    # Diagnóstico.
    print("\n===== DIAGNÓSTICO =====")
    print(f"Tipo de arma: {tipoarma}")
    print(f"Requisito consultado: {statusdesejado}")
    print(f"Status informado: {valorstatus2}")
    print(f"Coluna de scaling: {coluna_scaling}")
    print(f"Scaling escolhido: {valor_scaling}")

    print(f"\nCorrespondências de tipo: {filtro_tipo.sum()}")
    print(f"Correspondências de requisito: {filtro_status.sum()}")
    print(f"Correspondências de scaling: {filtro_scaling.sum()}")

    filtro_completo = filtro_tipo & filtro_status & filtro_scaling

    print(f"Correspondências dos três filtros: {filtro_completo.sum()}")

    # Mostrar os resultados.
    df_filtro = df.loc[filtro_completo]

    print("\n===== ARMAS ENCONTRADAS =====")

    if df_filtro.empty:
      print("Nenhuma arma corresponde aos três critérios.")

      # Mostrar armas do tipo escolhido para ajudar na investigação.
      armas_tipo = df.loc[filtro_tipo]

      print("\nExemplos de armas desse tipo:")
      print(
          armas_tipo[
              ["Weapon", statusdesejado, coluna_scaling]
          ].head(20).to_string(index=False)
      )

    else:
      print(df_filtro.to_string(index=False))

    print(f"\nTotal de armas encontradas: {len(df_filtro)}")

    return df_filtro

  def menu(self):
    print("\n===== WEAPON PICKER =====")
    print("1. Escolher o tipo de arma.")
    print("2. Escolher o status do personagem.")
    print("3. Escolher o scaling desejado.")
    print("4. Executar a filtragem.")
    print("5. Encerrar o processo.")

  def executar(self, df):
    continuar = True

    escolhertipoarma2 = None
    requerimentodesejado2 = None
    valorstatus2 = None
    scalingdesejado2 = None
    scalingtipodesejado2 = None

    scalingtipo = (
        "Scaling (+10/+5) STR",
        "Scaling (+10/+5) DEX",
        "Scaling (+10/+5) INT",
        "Scaling (+10/+5) FTH"
    )

    statusds = (
        "Requirements STR",
        "Requirements DEX",
        "Requirements INT",
        "Requirements FTH"
    )

    valorscaling = ("E", "D", "C", "B", "A", "S")

    listatiposarmas = (
        "Axe", "Bow", "Claw", "Crossbow",
        "Curved Greatsword", "Curved Sword", "Dagger", "Fist",
        "Great Hammer", "Greataxe", "Greatbow", "Greatsword",
        "Halberd", "Hammer", "Katana", "Piercing Sword",
        "Reaper", "Sacred Chime", "Spear", "Staff",
        "Straight Sword", "Talisman", "Ultra Greatsword", "Whip"
    )

    while continuar:
      self.menu()
      escolha = input("Digite a opção desejada: ")

      match escolha:
        case "1":
          escolhertipoarma2 = self.escolhertipoarma(
              df, listatiposarmas
          )

        case "2":
          requerimentodesejado2, valorstatus2 = self.requerimentostatus(
              df, statusds
          )

        case "3":
          scalingdesejado2, scalingtipodesejado2 = self.scalingdesejado(
              df, valorscaling, scalingtipo
          )

        case "4":
          if (
              escolhertipoarma2 is not None and
              requerimentodesejado2 is not None and
              valorstatus2 is not None and
              scalingdesejado2 is not None and
              scalingtipodesejado2 is not None
          ):
            resultado = self.filtragem(
                df,
                listatiposarmas,
                escolhertipoarma2,
                statusds,
                requerimentodesejado2,
                valorstatus2,
                valorscaling,
                scalingtipo,
                scalingdesejado2,
                scalingtipodesejado2
            )
          else:
            print("Execute as opções 1, 2 e 3 antes de filtrar.")

        case "5":
          continuar = False
          print("Processo encerrado.")

        case _:
          print("Opção inválida. Tente novamente.")

In [5]:
#Célula paa a execução do programa.
weaponpicker = Weaponpicker()
weaponpicker.executar(df)

===== WEAPON PICKER =====
1. Escolher o tipo de arma.
2. Escolher o status do personagem.
3. Escolher o scaling desejado.
4. Executar a filtragem.
5. Encerrar o processo.
Digite a opção desejada: 1

Selecione o tipo de arma desejado.
0 para escolher Axe.
1 para escolher Bow.
2 para escolher Claw.
3 para escolher Crossbow.
4 para escolher Curved Greatsword.
5 para escolher Curved Sword.
6 para escolher Dagger.
7 para escolher Fist.
8 para escolher Great Hammer.
9 para escolher Greataxe.
10 para escolher Greatbow.
11 para escolher Greatsword.
12 para escolher Halberd.
13 para escolher Hammer.
14 para escolher Katana.
15 para escolher Piercing Sword.
16 para escolher Reaper.
17 para escolher Sacred Chime.
18 para escolher Spear.
19 para escolher Staff.
20 para escolher Straight Sword.
21 para escolher Talisman.
22 para escolher Ultra Greatsword.
23 para escolher Whip.
Digite o número do tipo de arma: 1

===== WEAPON PICKER =====
1. Escolher o tipo de arma.
2. Escolher o status do personagem.
3. Escolher o scaling desejado.
4. Executar a filtragem.
5. Encerrar o processo.
Digite a opção desejada: 2

Selecione o atributo que deseja verificar.
0 para escolher Requirements STR.
1 para escolher Requirements DEX.
2 para escolher Requirements INT.
3 para escolher Requirements FTH.
Digite o número do atributo: 1
Digite o valor do seu status (1 a 99): 80

===== WEAPON PICKER =====
1. Escolher o tipo de arma.
2. Escolher o status do personagem.
3. Escolher o scaling desejado.
4. Executar a filtragem.
5. Encerrar o processo.
Digite a opção desejada: 3

Selecione o atributo do scaling.
0 para escolher Scaling (+10/+5) STR.
1 para escolher Scaling (+10/+5) DEX.
2 para escolher Scaling (+10/+5) INT.
3 para escolher Scaling (+10/+5) FTH.
Digite o número do atributo: 1

Selecione a letra de scaling desejada.
0 para escolher E.
1 para escolher D.
2 para escolher C.
3 para escolher B.
4 para escolher A.
5 para escolher S.
Digite o número da letra: 2

===== WEAPON PICKER =====
1. Escolher o tipo de arma.
2. Escolher o status do personagem.
3. Escolher o scaling desejado.
4. Executar a filtragem.
5. Encerrar o processo.
Digite a opção desejada: 4

===== DIAGNÓSTICO =====
Tipo de arma: Bow
Requisito consultado: Requirements DEX
Status informado: 80
Coluna de scaling: Scaling (+10/+5) DEX
Scaling escolhido: C

Correspondências de tipo: 6
Correspondências de requisito: 151
Correspondências de scaling: 42
Correspondências dos três filtros: 0

===== ARMAS ENCONTRADAS =====
Nenhuma arma corresponde aos três critérios.

Exemplos de armas desse tipo:
             Weapon Requirements DEX Scaling (+10/+5) DEX
    Dragonrider Bow               15                    D
      Composite Bow               12                    D
Black Bow of Pharis               18                    B
            Longbow               14                    D
          Short Bow               12                    D
   Darkmoon Longbow               16                    E

Total de armas encontradas: 0

===== WEAPON PICKER =====
1. Escolher o tipo de arma.
2. Escolher o status do personagem.
3. Escolher o scaling desejado.
4. Executar a filtragem.
5. Encerrar o processo.
Digite a opção desejada: 3

Selecione o atributo do scaling.
0 para escolher Scaling (+10/+5) STR.
1 para escolher Scaling (+10/+5) DEX.
2 para escolher Scaling (+10/+5) INT.
3 para escolher Scaling (+10/+5) FTH.
Digite o número do atributo: 1

Selecione a letra de scaling desejada.
0 para escolher E.
1 para escolher D.
2 para escolher C.
3 para escolher B.
4 para escolher A.
5 para escolher S.
Digite o número da letra: 2

===== WEAPON PICKER =====
1. Escolher o tipo de arma.
2. Escolher o status do personagem.
3. Escolher o scaling desejado.
4. Executar a filtragem.
5. Encerrar o processo.
Digite a opção desejada: 1

Selecione o tipo de arma desejado.
0 para escolher Axe.
1 para escolher Bow.
2 para escolher Claw.
3 para escolher Crossbow.
4 para escolher Curved Greatsword.
5 para escolher Curved Sword.
6 para escolher Dagger.
7 para escolher Fist.
8 para escolher Great Hammer.
9 para escolher Greataxe.
10 para escolher Greatbow.
11 para escolher Greatsword.
12 para escolher Halberd.
13 para escolher Hammer.
14 para escolher Katana.
15 para escolher Piercing Sword.
16 para escolher Reaper.
17 para escolher Sacred Chime.
18 para escolher Spear.
19 para escolher Staff.
20 para escolher Straight Sword.
21 para escolher Talisman.
22 para escolher Ultra Greatsword.
23 para escolher Whip.
Digite o número do tipo de arma: 11

===== WEAPON PICKER =====
1. Escolher o tipo de arma.
2. Escolher o status do personagem.
3. Escolher o scaling desejado.
4. Executar a filtragem.
5. Encerrar o processo.
Digite a opção desejada: 4

===== DIAGNÓSTICO =====
Tipo de arma: Greatsword
Requisito consultado: Requirements DEX
Status informado: 80
Coluna de scaling: Scaling (+10/+5) DEX
Scaling escolhido: C

Correspondências de tipo: 14
Correspondências de requisito: 151
Correspondências de scaling: 42
Correspondências dos três filtros: 3

===== ARMAS ENCONTRADAS =====
                  Weapon Requirements STR Requirements DEX Requirements INT Requirements FTH Requirements Weight Crit dmg bonus Normal DMG +10/+5 Phy Normal DMG +10/+5 Magic Normal DMG +10/+5 Fire Normal DMG +10/+5 Light Normal DMG +10/+5 Dark Auxiliary Damage Bleed Auxiliary Damage Poison Auxiliary Damage Frost Scaling (+10/+5) STR Scaling (+10/+5) DEX Scaling (+10/+5) INT Scaling (+10/+5) FTH Weapon Type     Damage Type             Skill Spell Buff Buffable Upgrade Material  AR Notes
 Hollowslayer Greatsword               14               18              NaN              NaN                 8.5            100                   264                     NaN                    NaN                     NaN                    NaN                    NaN                     NaN                    NaN                    D                    C                  NaN                  NaN  Greatsword Standard/Thrust            Stance        NaN        N            Scale 516   NaN
Wolf Knight's Greatsword               24               18              NaN              NaN                11.5            100                   230                     NaN                    NaN                     NaN                    NaN                    NaN                     NaN                    NaN                    C                    C                  NaN                  NaN  Greatsword Standard/Thrust         Wolfsword        NaN        N            Scale 473   NaN
     Wolnir's Holy Sword               13               13              NaN               13                 7.5            100                   250                     NaN                    NaN                     NaN                    NaN                    NaN                     NaN                    NaN                    D                    C                  NaN                  NaN  Greatsword        Standard Wrath of the Gods        NaN        N            Scale 423   NaN

Total de armas encontradas: 3

===== WEAPON PICKER =====
1. Escolher o tipo de arma.
2. Escolher o status do personagem.
3. Escolher o scaling desejado.
4. Executar a filtragem.
5. Encerrar o processo.
Digite a opção desejada: 2

Selecione o atributo que deseja verificar.
0 para escolher Requirements STR.
1 para escolher Requirements DEX.
2 para escolher Requirements INT.
3 para escolher Requirements FTH.
Digite o número do atributo: 1
Digite o valor do seu status (1 a 99): 30

===== WEAPON PICKER =====
1. Escolher o tipo de arma.
2. Escolher o status do personagem.
3. Escolher o scaling desejado.
4. Executar a filtragem.
5. Encerrar o processo.
Digite a opção desejada: 3

Selecione o atributo do scaling.
0 para escolher Scaling (+10/+5) STR.
1 para escolher Scaling (+10/+5) DEX.
2 para escolher Scaling (+10/+5) INT.
3 para escolher Scaling (+10/+5) FTH.
Digite o número do atributo: 0

Selecione a letra de scaling desejada.
0 para escolher E.
1 para escolher D.
2 para escolher C.
3 para escolher B.
4 para escolher A.
5 para escolher S.
Digite o número da letra: 2

===== WEAPON PICKER =====
1. Escolher o tipo de arma.
2. Escolher o status do personagem.
3. Escolher o scaling desejado.
4. Executar a filtragem.
5. Encerrar o processo.
Digite a opção desejada: 4

===== DIAGNÓSTICO =====
Tipo de arma: Greatsword
Requisito consultado: Requirements DEX
Status informado: 30
Coluna de scaling: Scaling (+10/+5) STR
Scaling escolhido: C

Correspondências de tipo: 14
Correspondências de requisito: 151
Correspondências de scaling: 47
Correspondências dos três filtros: 5

===== ARMAS ENCONTRADAS =====
                  Weapon Requirements STR Requirements DEX Requirements INT Requirements FTH Requirements Weight Crit dmg bonus Normal DMG +10/+5 Phy Normal DMG +10/+5 Magic Normal DMG +10/+5 Fire Normal DMG +10/+5 Light Normal DMG +10/+5 Dark Auxiliary Damage Bleed Auxiliary Damage Poison Auxiliary Damage Frost Scaling (+10/+5) STR Scaling (+10/+5) DEX Scaling (+10/+5) INT Scaling (+10/+5) FTH Weapon Type     Damage Type        Skill Spell Buff Buffable Upgrade Material  AR                   Notes
                Claymore               16               13              NaN              NaN                   9            100                   276                     NaN                    NaN                     NaN                    NaN                    NaN                     NaN                    NaN                    C                    D                  NaN                  NaN  Greatsword Standard/Thrust       Stance        NaN        Y         Titanite 493                     NaN
           Bastard Sword               16               10              NaN              NaN                   8            100                   276                     NaN                    NaN                     NaN                    NaN                    NaN                     NaN                    NaN                    C                    D                  NaN                  NaN  Greatsword        Standard        Stomp        NaN        Y         Titanite 493                     NaN
      Black Knight Sword               20               18              NaN              NaN                  10            100                   272                     NaN                    NaN                     NaN                    NaN                    NaN                     NaN                    NaN                    C                    D                  NaN                  NaN  Greatsword Standard/Thrust Perseverence        NaN        N        Twinkling 489  + 20% Damage to Demons
Wolf Knight's Greatsword               24               18              NaN              NaN                11.5            100                   230                     NaN                    NaN                     NaN                    NaN                    NaN                     NaN                    NaN                    C                    C                  NaN                  NaN  Greatsword Standard/Thrust    Wolfsword        NaN        N            Scale 473                     NaN
             Storm Ruler                0                0              NaN              NaN                  10            100                   260                     NaN                    NaN                     NaN                    NaN                    NaN                     NaN                    NaN                    C                    D                  NaN                  NaN  Greatsword        Standard   Storm King        NaN        N        Twinkling 451                     NaN

Total de armas encontradas: 5

===== WEAPON PICKER =====
1. Escolher o tipo de arma.
2. Escolher o status do personagem.
3. Escolher o scaling desejado.
4. Executar a filtragem.
5. Encerrar o processo.
Digite a opção desejada: 4

===== DIAGNÓSTICO =====
Tipo de arma: Greatsword
Requisito consultado: Requirements DEX
Status informado: 30
Coluna de scaling: Scaling (+10/+5) STR
Scaling escolhido: C

Correspondências de tipo: 14
Correspondências de requisito: 151
Correspondências de scaling: 47
Correspondências dos três filtros: 5

===== ARMAS ENCONTRADAS =====
                  Weapon Requirements STR Requirements DEX Requirements INT Requirements FTH Requirements Weight Crit dmg bonus Normal DMG +10/+5 Phy Normal DMG +10/+5 Magic Normal DMG +10/+5 Fire Normal DMG +10/+5 Light Normal DMG +10/+5 Dark Auxiliary Damage Bleed Auxiliary Damage Poison Auxiliary Damage Frost Scaling (+10/+5) STR Scaling (+10/+5) DEX Scaling (+10/+5) INT Scaling (+10/+5) FTH Weapon Type     Damage Type        Skill Spell Buff Buffable Upgrade Material  AR                   Notes
                Claymore               16               13              NaN              NaN                   9            100                   276                     NaN                    NaN                     NaN                    NaN                    NaN                     NaN                    NaN                    C                    D                  NaN                  NaN  Greatsword Standard/Thrust       Stance        NaN        Y         Titanite 493                     NaN
           Bastard Sword               16               10              NaN              NaN                   8            100                   276                     NaN                    NaN                     NaN                    NaN                    NaN                     NaN                    NaN                    C                    D                  NaN                  NaN  Greatsword        Standard        Stomp        NaN        Y         Titanite 493                     NaN
      Black Knight Sword               20               18              NaN              NaN                  10            100                   272                     NaN                    NaN                     NaN                    NaN                    NaN                     NaN                    NaN                    C                    D                  NaN                  NaN  Greatsword Standard/Thrust Perseverence        NaN        N        Twinkling 489  + 20% Damage to Demons
Wolf Knight's Greatsword               24               18              NaN              NaN                11.5            100                   230                     NaN                    NaN                     NaN                    NaN                    NaN                     NaN                    NaN                    C                    C                  NaN                  NaN  Greatsword Standard/Thrust    Wolfsword        NaN        N            Scale 473                     NaN
             Storm Ruler                0                0              NaN              NaN                  10            100                   260                     NaN                    NaN                     NaN                    NaN                    NaN                     NaN                    NaN                    C                    D                  NaN                  NaN  Greatsword        Standard   Storm King        NaN        N        Twinkling 451                     NaN

Total de armas encontradas: 5

===== WEAPON PICKER =====
1. Escolher o tipo de arma.
2. Escolher o status do personagem.
3. Escolher o scaling desejado.
4. Executar a filtragem.
5. Encerrar o processo.
Digite a opção desejada: 5
Processo encerrado.

Em suma, o código está funcionando de forma básica.
Ainda posso adicionar futuramente novas features.